<!DOCTYPE html>
<html lang="en">
<head>

    <title>Personal Manager</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="http://localhost/paw/personalManager/bootstrap/modernizr.min.js" type="text/javascript"></script>
    <link rel='stylesheet prefetch'
          href='http://localhost/paw/personalManager/bootstrap/bootstrap-3.2.0/dist/css/bootstrap.min.css'>
    <script src='http://localhost/paw/personalManager/bootstrap/js/jquery.min.js'></script>
    <script src='http://localhost/paw/personalManager/bootstrap/bootstrap-3.2.0/dist/js/bootstrap.min.js'></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <style>
        body {
            font: 400 15px Lato, sans-serif;
            line-height: 1.8;
            color: #7E221B;
        }

        h2 {
            font-size: 24px;
            text-transform: uppercase;
            color: #303030;
            font-weight: 600;
            margin-bottom: 30px;
        }

        h4 {
            font-size: 19px;
            line-height: 1.375em;
            color: #303030;
            font-weight: 400;
            margin-bottom: 30px;
        }

        .jumbotron {
            background-image: url('http://s3.amazonaws.com/digitaltrends-uploads-prod/2015/02/Enterprise-network-security.jpg');
            color: #fff;
            padding: 100px 25px;
            font-family: Montserrat, sans-serif;
            height: 500px;
        }


        .bg-grey {
            background-color: #f6f6f6;
        }

        .logo-small {
            color: #79AD36;
            font-size: 50px;
        }

        .logo {
            color: #79AD36;
            font-size: 170px;
            padding-left: 80px;
            padding-top: 25px;
        }

        .thumbnail {
            padding: 0 0 15px 0;
            border: none;
            border-radius: 0;
        }

        .thumbnail img {
            width: 100%;
            height: 100%;
            margin-bottom: 10px;
        }

        .carousel-control.right, .carousel-control.left {
            background-image: none;
            color: #79AD36;
        }

        .carousel-indicators li {
            border-color: #79AD36;
        }

        .carousel-indicators li.active {
            background-color: #79AD36;
        }

        .item h4 {
            font-size: 19px;
            line-height: 1.375em;
            font-weight: 400;
            font-style: italic;
            margin: 70px 0;
        }

        .item span {
            font-style: normal;
        }

        .panel {
            border: 1px solid #79AD36;
            border-radius: 0 !important;
            transition: box-shadow 0.5s;
        }

        .panel:hover {
            box-shadow: 5px 0px 40px rgba(0, 0, 0, .2);
        }

        .panel-footer .btn:hover {
            border: 1px solid #79AD36;
            background-color: #fff !important;
            color: #79AD36;
        }

        .panel-heading {
            color: #fff !important;
            background-color: #79AD36 !important;
            padding: 25px;
            border-bottom: 1px solid transparent;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }

        .panel-footer {
            background-color: white !important;
        }

        .panel-footer h3 {
            font-size: 32px;
        }

        .panel-footer h4 {
            color: #aaa;
            font-size: 14px;
        }

        .panel-footer .btn {
            margin: 15px 0;
            background-color: #79AD36;
            color: #fff;
        }

        .navbar {
            margin-bottom: 0;
            background-color: #79AD36;
            z-index: 9999;
            border: 0;
            font-size: 12px !important;
            line-height: 1.42857143 !important;
            letter-spacing: 4px;
            border-radius: 0;
            font-family: Montserrat, sans-serif;
        }

        .navbar li a, .navbar .navbar-brand {
            color: #fff !important;
        }

        .navbar-nav li a:hover, .navbar-nav li.active a {
            color: #79AD36 !important;
            background-color: #fff !important;
        }

        .navbar-default .navbar-toggle {
            border-color: transparent;
            color: #fff !important;
        }

        footer .glyphicon {
            font-size: 20px;
            margin-bottom: 20px;
            color: #79AD36;
        }

        .slideanim {
            visibility: hidden;
        }

        .slide {
            animation-name: slide;
            -webkit-animation-name: slide;
            animation-duration: 1s;
            -webkit-animation-duration: 1s;
            visibility: visible;
        }

        @keyframes slide {
            0% {
                opacity: 0;
                transform: translateY(70%);
            }
            100% {
                opacity: 1;
                transform: translateY(0%);
            }
        }

        @-webkit-keyframes slide {
            0% {
                opacity: 0;
                -webkit-transform: translateY(70%);
            }
            100% {
                opacity: 1;
                -webkit-transform: translateY(0%);
            }
        }

        @media screen and (max-width: 768px) {
            .col-sm-4 {
                text-align: center;
                margin: 25px 0;
            }

            .btn-lg {
                width: 100%;
                margin-bottom: 35px;
            }
        }

        @media screen and (max-width: 480px) {
            .logo {
                font-size: 150px;
            }
        }

        .blockquote-custom {
            padding: 3px 20px;
            font-size: 17.5px;
            border-left: 5px solid #eee;
            width: 50%;
            margin: 0 auto;
        }

        .blockquote-red {
            border-left: 5px solid #79AD36;
        }


        .footer-custom{
            border-bottom: 4px solid #3ea50b;
        }
    </style>
</head>
< id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">

<nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#myPage">KeepItSafe</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#services">SHËRBIME</a></li>
            <li><a href="#pricing">PLANET</a></li>
            <li><a href="#about">RRETH NESH</a></li>
            <li><a href="#contact">KONTAKT</a></li>
            <li><a href="login.php">LOGIN</a></li>
        </ul>
    </div>
</nav>


<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

        <div class="item active">
            <div class="jumbotron text-center">
                <h1>Kasaforta Infomative</h1>
                <blockquote class="blockquote-custom">
                    <p class="mb-0">Informacionet dhe dokumentat tuaja janë të rëndësishme,ruajini dhe aksesojini ato në
                        kasafortën tonë dixhitale!</p>
                </blockquote>
            </div>
        </div>

        <div class="item">

            <div class="jumbotron text-center">
                <h1>Krijoni llogarinë tuaj tani!</h1>
                <blockquote class="blockquote-custom">
                    <p class="mb-0">Përfitoni shërbimet tona dhe deri në 5GB falas!</p>
                </blockquote>
                <a class="btn btn-info" style="width: 160px; background-color: #00CC00" href="registration.php">Register</a></button>
            </div>
        </div>

        <div class="item">
            <div class="jumbotron text-center">
                <h1>Siguri dhe lehtësi</h1>
                <blockquote class="blockquote-custom">
                    <p class="mb-0">Siguri në ruajtje, lehtësi në menaxhimin e fileve!</p>
                </blockquote>
            </div>
        </div>

        <div class="item">
            <div class="jumbotron text-center">
                <h1></h1>
                <blockquote class="blockquote-custom">
                    <p class="mb-0">We keep your things secure!</p>
                </blockquote>
            </div>
        </div>
    </div>
</div>


<!-- Container (Services Section) -->
<div id="services" class="container-fluid text-center">
    <h2>SHËRBIMET</h2>
    <h4>Ne ofrojmë</h4>
    <br>
    <div class="row slideanim">
        <div class="col-sm-4">
            <span class="glyphicon glyphicon-lock logo-small"></span>
            <h4>Siguri</h4>
            <p>Ndalimi i aksesit të paautorizuar, nëpërmjet enkriptimit, secret token etj.</p>
        </div>
        <div class="col-sm-4">
            <span class="glyphicon glyphicon-leaf logo-small"></span>
            <h4>Lehtësi</h4>
            <p>..në përdorim dhe akses në çdo kohë</p>
        </div>

        <div class="col-sm-4">
            <span class="glyphicon glyphicon-folder-open logo-small"></span>
            <h4>Organizim</h4>
            <p>File dhe informacione të organizuara dhe lehtësisht të menaxhuesshme</p>
        </div>
    </div>
<br><br>
    <div class="row slideanim">
        <div class="col-sm-4">
            <span class="glyphicon glyphicon-ok logo-small"></span>
            <h4>5GB falas</h4>
            <p>Ju ofrojmë 5GB hapësirë ruajtëse falas!</p>
        </div>

    <div class="col-sm-4">
        <span class="glyphicon glyphicon-phone-alt logo-small"></span>
        <h4>Suport</h4>
        <p>Përgjigje brenda 24 orëve për cdo paqartësi..</p>
    </div>
    <div class="col-sm-4">
        <span class="glyphicon glyphicon-dashboard logo-small"></span>
        <h4 style="color:#303030;">Performancë</h4>
        <p>Lorem ipsum dolor sit amet..</p>
    </div>
</div>
</div>

<br><br>
<!--planet-->
<!-- Container (Pricing Section) -->
<div id="pricing" class="container-fluid">
    <div class="text-center">
        <h2>PLANET E SHËRBIMIT</h2>
        <h4>Zgjidh palnin që ju përshtatet më shumë</h4>
    </div>
    <div class="row slideanim">
        <div class="col-sm-4 col-xs-12">
            <div class="panel panel-default text-center">
                <div class="panel-heading">
                    <h1>Falas</h1>
                </div>
                <div class="panel-body">
                    <p><strong>20</strong> Lorem</p>
                    <p><strong>5</strong> GB</p>
                </div>
                <div class="panel-footer">
                    <h3>$0.00</h3>
                    <h4>në muaj</h4>
                    <button class="btn btn-lg">Regjistrohu</button>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-xs-12">
            <div class="panel panel-default text-center">
                <div class="panel-heading">
                    <h1>PRO</h1>
                </div>
                <div class="panel-body">
                    <p><strong>50</strong> Lorem</p>

                    <p><strong>10</strong> GB</p>
                </div>
                <div class="panel-footer">
                    <h3>$15</h3>
                    <h4>në muaj</h4>
                    <button class="btn btn-lg">Regjistrohu</button>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-xs-12">
            <div class="panel panel-default text-center">
                <div class="panel-heading">
                    <h1>PREMIUM</h1>
                </div>
                <div class="panel-body">
                    <p><strong>10</strong> Sit</p>
                    <p><strong>20</strong> GB</p>
                </div>
                <div class="panel-footer">
                    <h3>$20</h3>
                    <h4>në muaj</h4>
                    <button class="btn btn-lg">Regjistrohu</button>
                </div>
            </div>
        </div>
    </div>
</div>

<br><br>
<!-- Container (About Section) -->
<div id="about" class="container-fluid">
    <div class="row">
        <div class="col-sm-8">
            <blockquote class="blockquote-red">
                <p class="mb-0">RRETH NESH</p>
            </blockquote>
            <br>
            <h4>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                ex ea commodo consequat.</h4><br>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
                deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
                ut aliquip ex ea commodo consequat.</p>
        </div>
        <div class="col-sm-4">
            <span class="glyphicon  glyphicon-cloud logo"></span>
        </div>
    </div>
</div>


<!-- Container (Portfolio Section) -->
<div id="portfolio" class="container-fluid text-center bg-grey">

    <h2>Çfarë përdoruesit tanë thonë:</h2>
    <div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="https://media-exp1.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAeuAAAAJGU2NGU4OGQ0LTkyZTEtNDFlYi05OGUxLThmODA3NTBkZTBkNg.jpg" class="img-circle" alt="Cinque Terre" style="margin-left:45%;" width="100" height="60">
                <h4>"Kjo kompani është më e mira. Më ofron gjithë mundësitë për organzimin dhe ruajtjen e informacionit
                    tim personal!"<br><span>Besim Saraci</span></h4>
            </div>
            <div class="item">
                <img src="https://media-exp1.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAeuAAAAJGU2NGU4OGQ0LTkyZTEtNDFlYi05OGUxLThmODA3NTBkZTBkNg.jpg" class="img-circle" alt="Cinque Terre" style="margin-left:45%;" width="100" height="60">

                <h4>"Në këtë kohë me kaq llogari dhe passworde, është e duhura !"<br><span>Malvina Xhabafti</span></h4>
            </div>
            <div class="item">
                <img src="https://media-exp1.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAeuAAAAJGU2NGU4OGQ0LTkyZTEtNDFlYi05OGUxLThmODA3NTBkZTBkNg.jpg" class="img-circle" alt="Cinque Terre" style="margin-left:45%;" width="100" height="60">

                <h4>"Mund të kem dokumentet e mia kudo që jam lehtësisht, faleminderit!"<br><span>Eugerta Haris</span>
                </h4>
            </div>
        </div>
    </div>
</div>


<!-- Container (Contact Section) -->
<div id="contact" class="container-fluid bg-grey">
    <h2 class="text-center">Kontakt</h2>
    <div class="row">
        <div class="col-sm-5">
            <p>Na kontaktoni për çdo paqartësi dhe ne do ju përgjigjemi brenda 24 orëve</p>
            <p><span class="glyphicon glyphicon-map-marker"></span> Tiranë, AL</p>
            <p><span class="glyphicon glyphicon-phone"></span> +355 5566 777</p>
            <p><span class="glyphicon glyphicon-envelope"></span> kasafortaDixhitale@gmail.com</p>
        </div>
        <div class="col-sm-7 slideanim">
            <div class="row">
                <div class="col-sm-6 form-group">
                    <input class="form-control" id="name" name="name" placeholder="Emri" type="text" required>
                </div>
                <div class="col-sm-6 form-group">
                    <input class="form-control" id="email" name="email" placeholder="Email" type="email" required>
                </div>
            </div>
            <textarea class="form-control" id="comments" name="comments" placeholder="komenti" rows="5"></textarea><br>
            <div class="row">
                <div class="col-sm-12 form-group">
                    <button class="btn btn-default pull-right" type="submit">Dërgo</button>
                </div>
            </div>
        </div>
    </div>
</div>

<footer class="container-fluid text-center footer-custom">
    <a href="#myPage" title="To Top">
        <span class="glyphicon glyphicon-chevron-up"></span>
    </a>
    <p>Copyright Besim Saraci</a></p>
</footer>

<script>
    $(document).ready(function () {
        // Add smooth scrolling to all links in navbar + footer link
        $(".navbar a, footer a[href='#myPage']").on('click', function (event) {
            // Make sure this.hash has a value before overriding default behavior
            if (this.hash !== "") {
                // Prevent default anchor click behavior
                event.preventDefault();

                // Store hash
                var hash = this.hash;

                // Using jQuery's animate() method to add smooth page scroll
                // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
                $('html, body').animate({
                    scrollTop: $(hash).offset().top
                }, 900, function () {

                    // Add hash (#) to URL when done scrolling (default click behavior)
                    window.location.hash = hash;
                });
            } // End if
        });

        $(window).scroll(function () {
            $(".slideanim").each(function () {
                var pos = $(this).offset().top;

                var winTop = $(window).scrollTop();
                if (pos < winTop + 600) {
                    $(this).addClass("slide");
                }
            });
        });
    })
</script>
</body>
</html>
