<?php
include ('../functions.php');
$loginAction = getActionUrl('login');

?>
<!DOCTYPE html>
<html lang="en" >

<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <script src="http://localhost/paw/personalManager/bootstrap/modernizr.min.js" type="text/javascript"></script>
    <link rel='stylesheet prefetch' href='http://localhost/paw/personalManager/bootstrap/bootstrap-3.2.0/dist/css/bootstrap.min.css'>
    <link rel='stylesheet prefetch' href='http://localhost/paw/personalManager/bootstrap/bootstrap-3.2.0/dist/css/bootstrap-theme.min.css'>
    <link rel='stylesheet prefetch' href='http://localhost/paw/personalManager/bootstrap/bootstrap-validator/css/bootstrapValidator.min.css'>
    <link rel="stylesheet" href="http://localhost/paw/personalManager/skin/css/style.css">
    <script src='http://localhost/paw/personalManager/bootstrap/js/jquery.min.js'></script>
    <script src='http://localhost/paw/personalManager/bootstrap/bootstrap-3.2.0/dist/js/bootstrap.min.js'></script>
    <script src='http://localhost/paw/personalManager/bootstrap/bootstrap-validator/js/bootstrapvalidator.min.js'></script>
    <script  src="http://localhost/paw/personalManager/skin/js/login_validation.js"></script>


</head>

<body>

<div class="container" style="padding: 0px;">
    <nav class="navbar  navbar-fixed-top">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href=homepage.phtml">KeepItSafe</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="registration.phtml">REGISTER</a></li>
            </ul>
        </div>
    </nav>
    <br><br>

    <form  style="height: 550px; border-radius: 0px" class="well form-horizontal" action="<?php echo $loginAction?>" method="post"  id="login_form">
        <fieldset>

            <!-- Form Name -->
            <legend><center><h2><b>Login</b></h2></center></legend><br>
            <center><a href="http://localhost/paw/personalManager/views/registration.phtml">Not a Member ?</a></center>


            <!-- Text input-->
            <div class="form-group">
                <label class="col-md-4 control-label">E-Mail</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                        <input name="email" placeholder="E-Mail Address" class="form-control"  type="text">
                    </div>
                </div>
            </div>


            <!-- Text input-->

            <div class="form-group">
                <label class="col-md-4 control-label" >Password</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <input name="user_password" placeholder="Password" class="form-control"  type="password">
                    </div>
                </div>
            </div>


            <!-- Success message -->
            <div class="alert alert-success" role="alert" id="success_message">Success <i class="glyphicon glyphicon-thumbs-up"></i> Success!.</div>

            <!-- Button -->
            <div class="form-group">
                <label class="col-md-4 control-label"></label>
                <div class="col-md-4"><br>
                    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<button type="submit" class="btn btn-warning" >&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspLogin <span class="glyphicon glyphicon-send"></span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</button>
                </div>
            </div>

        </fieldset>
    </form>
</div>

<footer class="container-fluid text-center footer-custom">


    <p>Copyright Besim Saraci</p>
</footer>
</div>




</body>

</html>
