<?php
$registrationAction = getActionUrl('registration');
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Become a Member</title>
    <script src="http://localhost/paw/personalManager/bootstrap/modernizr.min.js" type="text/javascript"></script>
    <link rel='stylesheet prefetch' href='http://localhost/paw/personalManager/bootstrap/bootstrap-validator/css/bootstrapValidator.min.css'>
    <link rel="stylesheet" href="http://localhost/paw/personalManager/skin/css/style.css">
    <script src='http://localhost/paw/personalManager/bootstrap/js/jquery.min.js'></script>
    <script src='http://localhost/paw/personalManager/bootstrap/bootstrap-validator/js/bootstrapvalidator.min.js'></script>
    <link href="http://localhost/paw/personalManager/datepicker/css/bootstrap-datepicker.css">
    <script src="http://localhost/paw/personalManager/datepicker/js/bootstrap-datepicker.js"></script>
    <script src="http://localhost/paw/personalManager/skin/js/register_validation.js"></script>
    <script src='http://localhost/paw/personalManager/bootstrap/bootstrap-3.2.0/dist/js/bootstrap.min.js'></script>
    <link rel='stylesheet prefetch' href='http://localhost/paw/personalManager/bootstrap/bootstrap-3.2.0/dist/css/bootstrap.min.css'>
    <link rel='stylesheet prefetch' href='http://localhost/paw/personalManager/bootstrap/bootstrap-3.2.0/dist/css/bootstrap-theme.min.css'>


</head>

<body>

<div class="container">

    <form class="well form-horizontal" action="<?php echo $registrationAction ?>" method="post" id="contact_form">
        <fieldset>

            <!-- Form Name -->
            <legend>
                <center><h2><b>Become a Member</b></h2></center>
            </legend>
            <center><a href="http://localhost/paw/personalManager/views/login.phtml">Already a Member ?</a></center>

            <!-- Text input-->

            <div class="form-group">
                <label class="col-md-4 control-label">First Name</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input name="first_name" placeholder="First Name" class="form-control" type="text">
                    </div>
                </div>
            </div>

            <!-- Text input-->

            <div class="form-group">
                <label class="col-md-4 control-label">Last Name</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input name="last_name" placeholder="Last Name" class="form-control" type="text">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label">Date of Birth</label>
                <div class="col-md-4 selectContainer">
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                        <input type="text" name="birth_date" class="form-control" placeholder="Date of Birth">
                    </div>
                </div>
            </div>

            <!-- Text input-->

            <div class="form-group">
                <label class="col-md-4 control-label">Username</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input name="user_name" placeholder="Username" class="form-control" type="text">
                    </div>
                </div>
            </div>

            <!-- Text input-->

            <div class="form-group">
                <label class="col-md-4 control-label">Password</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <input name="user_password" placeholder="Password" class="form-control" type="password">
                    </div>
                </div>
            </div>

            <!-- Text input-->

            <div class="form-group">
                <label class="col-md-4 control-label">Confirm Password</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <input name="confirm_password" placeholder="Confirm Password" class="form-control"
                               type="password">
                    </div>
                </div>
            </div>

            <!-- Text input-->
            <div class="form-group">
                <label class="col-md-4 control-label">E-Mail</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                        <input name="email" placeholder="E-Mail Address" class="form-control" type="text">
                    </div>
                </div>
            </div>


            <!-- Text input-->

            <div class="form-group">
                <label class="col-md-4 control-label">Contact No.</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
                        <input name="contact_no" placeholder="(639)" class="form-control" type="text">
                    </div>
                </div>
            </div>

            <!-- Select Basic -->

            <!-- Success message -->
            <div class="alert alert-success" role="alert" id="success_message">Success <i
                    class="glyphicon glyphicon-thumbs-up"></i> Success!.
            </div>

            <!-- Button -->
            <div class="form-group">
                <label class="col-md-4 control-label"></label>
                <div class="col-md-4"><br>
                    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                    <button type="submit" class="btn btn-warning">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspSUBMIT <span
                            class="glyphicon glyphicon-send"></span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                    </button>
                </div>
            </div>

        </fieldset>
    </form>
</div>
</div>


<script>
    $('.container .input-group.date').datepicker({
        autoclose: true,
        todayHighlight: true
    });
</script>
</body>

</html>
